<?php
/* =========================================================
   reports_init.php — Shared Logic for All Reports
   ========================================================= */

session_start();
if (isset($_GET['reset'])) { header("Location: reports.php"); exit; }
if (!isset($_SESSION['user_id'])) { header("Location: login.php"); exit; }

require_once 'config.php'; 

// --- FUNÇÕES AUXILIARES ---
function h($v) { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function getParam($k) { return (isset($_GET[$k]) && $_GET[$k]!=='') ? $_GET[$k] : null; }

// --- DADOS DA EMPRESA E USUÁRIO ---
$user_id = $_SESSION['user_id'];
$headerData = [];
try {
    $stmtH = $conn->prepare("SELECT u.full_name, c.name as company_name, c.address, c.phone, c.email, c.logo_path FROM users u LEFT JOIN company c ON u.company_id = c.company_id WHERE u.user_id = ?");
    $stmtH->bind_param("i", $user_id);
    $stmtH->execute();
    $headerData = $stmtH->get_result()->fetch_assoc();
} catch (Exception $e) { /* Ignore */ }

// --- CARREGAMENTO DE FILTROS GERAIS ---
$lots = $conn->query("SELECT lot_id, name FROM lot ORDER BY name");
$types = $conn->query("SELECT type_id, breed FROM animal_types ORDER BY breed");
$feeds = $conn->query("SELECT feed_id, name FROM feed ORDER BY name");
$cats = $conn->query("SELECT DISTINCT category FROM operational_costs WHERE category != ''");

// --- HELPER PARA QUERY SQL ---
function buildQueryCondition(&$w, &$types, &$params, $sqlPart, $typeStr, $val){ 
    if($val!==null && $val!==''){ $w[]=$sqlPart; $types.=$typeStr; $params[]=$val; } 
}

// --- FUNÇÃO DE EXPORTAÇÃO (PDF/CSV) ---
function handleExport($export, $rows, $columns, $headerData, $tableTitle, $appliedFiltersText) {
    if (!$rows) return;
    if ($export == 'csv') {
        header('Content-Type: text/csv'); header('Content-Disposition: attachment; filename="report.csv"');
        $out = fopen('php://output', 'w'); fputcsv($out, $columns);
        foreach($rows as $r) fputcsv($out, $r); fclose($out); exit;
    }
    if ($export == 'pdf') {
        ?>
        <!DOCTYPE html><html><head><meta charset="UTF-8"><title>Report</title>
        <style>
            body { font-family: sans-serif; font-size: 12px; color: #333; }
            .header { border-bottom: 2px solid #4ade80; padding-bottom: 10px; margin-bottom: 20px; }
            .header h1 { margin: 0; color: #1e293b; font-size: 20px; }
            .header p { margin: 2px 0; color: #64748b; }
            table { width: 100%; border-collapse: collapse; margin-top: 10px; }
            th { background: #f1f5f9; text-align: left; padding: 8px; border-bottom: 1px solid #cbd5e1; font-size: 11px; text-transform: uppercase; }
            td { padding: 8px; border-bottom: 1px solid #e2e8f0; }
            .meta { float: right; text-align: right; font-size: 10px; }
        </style>
        </head><body onload="window.print()">
            <div class="header">
                <div class="meta">Generated by: <?= h($headerData['full_name'] ?? 'System') ?><br>Date: <?= date('d/m/Y H:i') ?></div>
                <h1><?= h($headerData['company_name'] ?? 'Farm Project') ?></h1>
                <p><?= h($headerData['address'] ?? '') ?> | <?= h($headerData['email'] ?? '') ?></p>
                <p><strong>Report:</strong> <?= h($tableTitle) ?></p>
                <?php if($appliedFiltersText): ?><p style="font-size:11px; font-style:italic;">Filters: <?= implode(", ", $appliedFiltersText) ?></p><?php endif; ?>
            </div>
            <table><thead><tr><?php foreach($columns as $c) echo "<th>$c</th>"; ?></tr></thead><tbody><?php foreach($rows as $r){ echo "<tr>"; foreach($r as $v) echo "<td>".h($v)."</td>"; echo "</tr>"; } ?></tbody></table>
        </body></html>
        <?php exit;
    }
}
?>